name: 'Slack Notify'
description: 'Send a Slack notification based on input parameters'

inputs:
  run_status:
    description: 'The status of the run'
    required: true
  channel_id:
    description: 'The ID of the channel'
    required: true
  service_name:
    description: 'The name of the service'
    required: true
  run_number:
    description: 'The run number'
    required: true
  branch_name:
    description: 'The branch name'
    required: true
  workflow_type:
    description: 'The type of the workflow'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send Slack Notification
      if: ${{ inputs.run_status == 'succeeded' }}
      run: |
        echo "Run Status: ${{ inputs.run_status }}"
        echo "Channel ID: ${{ inputs.channel_id }}"
        echo "Service Name: ${{ inputs.service_name }}"
        echo "Run Number: ${{ inputs.run_number }}"
        echo "Branch Name: ${{ inputs.branch_name }}"
        echo "Workflow Type: ${{ inputs.workflow_type }}"
      shell: bash