name: 'Post to Slack'
description: 'An action to post a message to a Slack channel based on the workflow run status.'
author: 'Your Name'

inputs:
  run_status:
    description: 'The status of the workflow run.'
    required: true
  channel_id:
    description: 'The Slack channel ID to post the message to.'
    required: true
  service_name:
    description: 'The name of the service related to the workflow.'
    required: true
  workflow_type:
    description: 'The type of workflow being run.'
    required: true
  run_number:
    description: 'The number of the current workflow run.'
    required: true
  run_id:
    description: 'The ID of the current workflow run.'
    required: true
  branch_name:
    description: 'The name of the branch being built.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run custom script
      run: |
        echo "Run ID: ${{ inputs.run_id }}"
        node slack/slack_utils.js "123"
      shell: bash

    - name: Post to Slack on failure
      if: ${{ inputs.run_status == 'failure' }}
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: '${{ inputs.channel_id }}'
        payload: |
          {
            "text": ":red_circle: `${{ inputs.service_name }} ${{ inputs.workflow_type }} workflow` :red_circle:\n\n*Status:*\nfailure\n\n*Run:*\n<https://www.ynet.co.il|Run number ${{ inputs.run_number }}>\n\n*Branch:*\n${{ inputs.branch_name }}\n\n*Released Services:*\n${{ inputs.service_name }}"
          }

    - name: Post to Slack on success
      if: ${{ inputs.run_status == 'succeeded' }}
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: '${{ inputs.channel_id }}'
        payload: |
          {
            "text": ":white_check_mark: `${{ inputs.service_name }} ${{ inputs.workflow_type }} workflow` :white_check_mark:\n\n*Status:*\nsucceeded\n\n*Run:*\n<https://www.ynet.co.il|Run number ${{ inputs.run_number }}>\n\n*Branch:*\n${{ inputs.branch_name }}\n\n*Released Services:*\n${{ inputs.service_name }}"
          }