name: 'Send Slack Message'
description: 'Sends a message to a Slack webhook URL'
author: 'Tzahi Bar'
inputs:
  workflow_name:
    description: 'The name of the workflow'
    required: true
  run_number:
    description: 'The run number'
    required: true
  branch_name:
    description: 'The branch name'
    required: true
outputs:
  status:
    description: 'The HTTP status code of the request'
runs:
  using: 'node20'
  main: 'index.js'