name: 'Post to Slack'
description: 'An action to post a message to a Slack channel based on the workflow run status.'
author: 'Your Name'

inputs:
  run_status:
    description: 'The status of the workflow run.'
    required: true
  channelId:
    description: 'The Slack channel ID to post the message to.'
    required: true
  service_name:
    description: 'The name of the service related to the workflow.'
    required: true
  workflow_type:
    description: 'The type of workflow being run.'
    required: true
  run_number:
    description: 'The number of the current workflow run.'
    required: true
  branch_name:
    description: 'The name of the branch being built.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Post to a Slack channel
      if: ${{ inputs.run_status == 'failure' }}
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: '${{ inputs.channelId }}'
        payload: |
          {
            "text": ":red_circle: `${{ inputs.service_name }} ${{ inputs.workflow_type }} workflow` :red_circle:\n*Status:*\nfailure\n\n*Run:*\n<https://www.ynet.co.il|Run number ${{ inputs.run_number }}>\n\n*Branch:*\n${{ inputs.branch_name }}\n\n*Released Services:*\n${{ inputs.service_name }}"
          }