name: 'Send Slack Message'
description: 'Sends a message to a Slack webhook URL'
author: 'Tzahi Bar'
inputs:
  webhook-url:
    description: 'The Slack webhook URL to send the message to'
    required: true
  message:
    description: 'The message to send to Slack'
    required: true
outputs:
  status:
    description: 'The HTTP status code of the request'
runs:
  using: 'node20'
  main: 'index.js'