name: Example Workflow

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some tests
        run: exit 1  # Simulating a failure

      - name: Post to Slack on failure
        uses: tzahibar/slack-notify@main
        with:
          run_status: ${{ job.status }}
          channelId: 'your-slack-channel-id'
          service_name: 'example-service'
          workflow_type: 'build'
          run_number: ${{ github.run_number }}
          branch_name: ${{ github.ref_name }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}


#      - name: Post to a Slack channel
#        if: ${{ inputs.run_status == 'failure' }}
#        id: slack
#        uses: slackapi/slack-github-action@v1.26.0
#        with:
#          channel-id: '${{ inputs.channelId }}'
#          payload: |
#            {
#              "text": ":red_circle: `${{ inputs.service_name }} ${{ inputs.workflow_type }} workflow` :red_circle:\n*Status:*\nfailure\n\n*Run:*\n<https://www.ynet.co.il|Run number ${{ inputs.run_number }}>\n\n*Branch:*\n${{ inputs.branch_name }}\n\n*Released Services:*\n${{ inputs.service_name }}"
#            }
#        env:
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20' # or any other Node.js version you need
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: install slack
#        run: npm install @slack/web-api
#
#      - name: Notify Slack
#        run: |
#          node slack/slack.js ${{ secrets.SLACK_TOKEN }} ${{ github.event.inputs.workflow_name }} ${{ github.event.inputs.service_name }} ${{ github.event.inputs.run_number }} ${{ github.event.inputs.branch_name }}
#        env:
#          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
#
#      - name: Send Slack message
#        id: slacks
#        uses: tzahibar/slack-notify@main
#        with:
#          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
#          message: 'Hello ${{ inputs.serviceName }}, DONE!'