name: Slack notification

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        run: slack-notify.js
        env:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: 'Hello from GitHub Actions!'
