name: Slack Action

on:
  workflow_dispatch:
    inputs:
      channelId:
        description: 'The ID of the channel'
        required: true
      service_name:
        description: 'The name of the service'
        required: true
      run_number:
        description: 'The run number'
        required: true
      branch_name:
        description: 'The branch name'
        required: true

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    name: Slack notification
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send custom JSON data to Slack workflow
        id: slack_notify
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ github.event.inputs.channelId }}
          slack-message: 'Hello ${{ github.actor }}, DONE!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or any other Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: install slack
        run: npm install @slack/web-api

      - name: Notify Slack
        run: |
          node slack/slack.js ${{ secrets.SLACK_TOKEN }} ${{ github.event.inputs.workflow_name }} ${{ github.event.inputs.service_name }} ${{ github.event.inputs.run_number }} ${{ github.event.inputs.branch_name }}
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Send Slack message
        id: slack
        uses: tzahibar/slack-notify@main
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: 'Hello ${{ inputs.serviceName }}, DONE!'