name: Slack Action

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'The name of the workflow'
        required: true
      run_number:
        description: 'The run number'
        required: true
      branch_name:
        description: 'The branch name'
        required: true

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    name: Slack notification
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Env vars
        run: |
          echo "GITHUB_ACTOR: GITHUB_ACTOR"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or any other Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Install axios
        run: npm install axios

      - name: Notify Slack
        run: |
          node slack/slack.js ${{ secrets.SLACK_WEBHOOK_URL }} ${{ inputs.workflow_name }} ${{ inputs.run_number }} ${{ inputs.branch_name }}

      - name: Send Slack message
        id: slack
        uses: tzahibar/slack-notify@main
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: 'Hello ${{ inputs.serviceName }}, DONE!'