on:
  workflow_dispatch:
    inputs:
      serviceName:
        description: 'Service name'
        required: true

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Slack notification
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # or any other Node.js version you need

      - name: Send Slack message
        id: slack
        uses: tzahibar/slack-notify@main
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: 'Hello ${{ inputs.serviceName }} from GitHub Actions!'